version: '2.4'

networks:
  default:
    external:
      name: default-network

services:
  monitorrent-tests:
    build: 
      context: .
      dockerfile: Dockerfile.tests
    volumes:
      - ./tests/cassettes:/var/www/monitorrent/tests/cassettes:rw
