FROM python:3-slim-buster

WORKDIR /var/www/monitorrent

COPY requirements*.txt /var/www/monitorrent/

RUN pip install --no-cache-dir -r /var/www/monitorrent/requirements.txt -r /var/www/monitorrent/requirements-dev.txt

COPY . .

CMD ["py.test", "--disable-warnings"]
